name: RepairTheItem
main: repair\pand\Main
author: pand_jxsper
version: 1.0.0-BETA
api: 3.0.0

permissions:
  repairtheitem.command:
    description: Gives your players the access to the repair command!
